 #Birthday Event
a=input("The birthday person's first name")
b=input("The birthday person's last name")
c=input("How old person is ?")
d=int(input("The number of friends invited?"))
e=int(input("Cost of each party favor"))
f=int(input("Cost of each cake"))
g=int(input("pizza cost"))
h=int(input("water cost"))
i=(3*d+10+1)
cake=(i*2)
pizza =round((2*i/8))
k=round((1.5*i))
l=(d*e)
m=(cake*g +pizza*g + k*h + d*e)
n=round((m/i))
print("Birthday person's name is",a,b,"and age is",c)
print("Number of people attending party =",i)
print("Number of pizzas =",pizza)
print("Liters of drinks =",k,"litrs.")
print("Total cost =",m)
print("cost per person =",n)